name: Container image build

on:
  push:
    branches:
      - develop
      - master
    paths:
      - "Containerfile"
  pull_request:
    branches:
      - master
    paths:
      - "Containerfile"
jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      name: Buildah action
      with:
        image: ${{ github.repository }}
        tags: ${{ github.sha }}
        containerfiles: |
          ./Containerfile
