name: Buildah Build

on:
  push:
    branches:
      - develop
      - master
    paths:
      - "Containerfile"
  pull_request:
    branches:
      - master
    paths:
      - "Containerfile"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    # https://github.com/redhat-actions/buildah-build
    - name: Buildah build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: mpv
        tags: latest ${{ github.ref_name }}
        containerfiles: |
          ./Containerfile
