name: Buildah Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build_n_push:
    name: Build and push
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      
    # https://github.com/redhat-actions/buildah-build
    - name: Buildah build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: mpv
        tags: latest ${{ github.ref_name }}
        containerfiles: |
          ./Containerfile

    # https://github.com/redhat-actions/push-to-registry
    - name: Push To docker.io
      id: push-to-docker-io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/cremuzzi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

